import Head from 'next/head'
import { useState,useEffect } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Coinsection from './Coinsection/Coinsection'
import SearchBar from './SearchBar/SearchBar'

export default function Home({ filteredCoins }) {

  const [search, setsearch] = useState('');

  const allCoins = filteredCoins.filter(coins => coins.name.toLowerCase().includes(search.toLowerCase()));
  
  const handleChange = (e) => {
    e.preventDefault();
    setsearch(e.target.value.toLowerCase());
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>CryptoTracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <section><div className="heading"><h1>Crypto Tracker</h1></div></section>
     <SearchBar onChange = {handleChange} />
     <Coinsection items = {allCoins}/>

     

    </div>
  )
}

export const getServerSideProps = async () =>
{

  const coins = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=20&page=1&sparkline=false');
  const filteredCoins = await coins.json();

return (
  
  {props:{filteredCoins}}
  

  );

};